pipeline {
    agent any
    stages {
        stage('image build') {
            steps {
                script {
                    def packageJson = readJSON file: 'api/package.json'
                    def packageJSONVersion = packageJson.version
                    echo "${packageJSONVersion}"
                    echo 'building image'
                    sh "docker build -t amanmohammad2608/lmsfront:${packageJSONVersion} ."
                    echo 'image build done' 
            }
        }
        }
    }
}